### ISSUE TITLE
Where's the connection to deep learning?

### ISSUE THREAD

**Issue by shyamalschandra** [XanaduAI/quantum-learning#1]
Where's the connection to deep learning?

**Comment by co9olguy** [comment]
Hi there,

In this repo, we have example code for a specific task: decomposing quantum state preparations and compiling quantum gates. The connection to deep learning is that we use the TensorFlow quantum simulator backend of Strawberry Fields and the backpropagation-based optimization tools within TensorFlow to solve the stated problem. You can think of it as a deep-learning-style model of a quantum circuit, rather than the more typical deep-learning neural network.

By the way, this repo contains example code for a specific research paper. If you are looking for more general examples and documentation on quantum machine learning and Strawberry Fields, the best place to look is the main SF repo (see the response to this similar issue there: https://github.com/XanaduAI/strawberryfields/issues/33)
